- hosts: all
  tasks:
  - name: run modprobe
    shell: sudo modprobe br_netfilter
  
  - name: kernel parameter
    shell: echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables
  
  - name: add repo
    copy:
       dest: /etc/yum.repos.d/kubernetes.repo
       content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
          
  
  - name: install kubeadm kubectl
    shell: sudo yum install kubeadm kubectl docker -
  - name: start kubelet and docker 
    shell: |
       sudo systemctl enable kubelet
       sudo systemctl start kubelet
       sudo systemctl enable docker
       sudo systemctl start docker
       sudo swapoff -a
       kubeadm init
       mkdir -p $HOME/.kube
       sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
       sudo chown $(id -u):$(id -g) $HOME/.kube/config
