
- name: test 1
  shell: |
     sudo apt update
     sudo apt install -y docker.io
     sudo systemctl enable docker.service --now
     swapoff -a
     echo "net.bridge.bridge-nf-call-iptables=1" | sudo tee -a /etc/sysctl.conf
     echo "net.ipv4.ip_forward=1" | sudo tee -a /etc/sysctl.conf
     sudo sysctl -p
     sudo apt install -y apt-transport-https curl
     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
     sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
     curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
     sudo mkdir -p /etc/yum.repos.d
     sudo touch /etc/yum.repos.d/kubernetes.repo


- name: Add k8s repository
  apt_repository:
     repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
     state: present
     filename: kubernetes
     update_cache: yes



- name: test 2
  shell: |
     sudo apt-get update
     sudo apt-get install -y docker-ce=5:20.10.7~3-0~ubuntu-$(lsb_release -cs) kubelet=1.21.1-00 kubeadm=1.21.1-00 kubectl=1.21.1-00
     sudo apt-mark hold docker-ce kubelet kubeadm kubectl
     swapoff -a
     sudo kubeadm init --apiserver-advertise-address {{ ansible_eth0.ipv4.address }} --pod-network-cidr 10.244.0.0/16 --ignore-preflight-errors=all --token 1exb8s.2t4k3b5syfc3jfmo
     #mkdir -p $HOME/.kube
     #sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
     #sudo chown $(id -u):$(id -g) $HOME/.kube/config
     #sudo kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
     #sudo kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml
     
- name: create .kube directory
  file:
    path: /home/.kube
    state: directory

- name: check kubectl
  shell: |
    sudo cp -i /etc/kubernetes/admin.conf /home/.kube/config
    sudo chown $(id -u):$(id -g) /home/.kube/conifg
    kubectl get nodes
    
- name: the file
    template:
      src: ./kubia.config.j2
      dest: $HOME/k8-kubia1.yaml
  
